# Application/HelloBundle/Resources/config/doctrine/metadata/orm/Application.HelloBundle.Entity.User.dcm.yml
Application\HelloBundle\Entity\Job:
    type: entity
    table: job
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255        
        company:
            type: string
            length: 255
        logo:
            type: string
            length: 255
        url:
            type: string
            length: 255
        position:
            type: string
            length: 255
        location:
            type: string
            length: 255
        description:
            type: string
            length: 4000
        how_to_apply:
            type: string
            length: 255
        token:
            type: string
            length: 255
        is_public:
            type: boolean
        is_activated:
            type: boolean
        email:
            type: string
            length: 255
        expires_at:
            type: datetime
    manyToOne:
        category:
          targetEntity: Category
          inversedBy: job
          JoinColumn:
            name: category_id
            referencedColumnName: id
          
     
            
          
            
       
